version: 2.1
executors:
  default:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
        environment:
          BUNDLER_VERSION: 2.1.2
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: booksapp
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: tugino_itte_dojo
          POSTGRES_PASSWORD: password
          POSTGRES_DB: tugino_itte_dojo_test
commands:  
  setup:  
    steps:  
      - checkout  
      - run:  
          name: Update bundler
          command: gem update bundler  
      - run:  
          name: Which bundler? 
          command: bundle -v

      - restore_cache:
          keys:  
            - gem-cache-v2-{{ checksum "Gemfile.lock" }}  
            - gem-cache-v2-  

      - run:  
          name: Bundle Install  
          command: bundle check|| bundle install

      - save_cache: 
          key: gem-cache-v2-{{ checksum "Gemfile.lock" }}  
          paths:  
            - vendor/bundle  

      - restore_cache:  
          keys:  
            - yarn-cache-v1-{{ checksum "yarn.lock" }}  
            - yarn-cache-v1-  

      - run:  
          name: Yarn Install  
          command: yarn install --cache-folder ~/.cache/yarn  

      - save_cache:  
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}  
          paths:  
            - ~/.cache/yarn  

jobs:  
  test:  
    executor: default
    environment:  
      RAILS_ENV: test  
    steps:  
      - checkout  
      - setup
      - run:
          name: db_wait
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: assets:precompile
          command: bin/rails assets:precompile

      - run:
          name: rubocop
          command: |
            bundle exec rubocop -c .rubocop.yml

      - run:
          name: Rails Test
          command: |
            bin/rails spec
workflows:  
  build_and_test:  
    jobs:  
      - test  
